from app.database import Base
from .user import User
from .job_description import JobDescription
from .cv_file import CVFile
from .candidate_profile import CandidateProfile
from .skill import Skill
from .experience import Experience
from .education import Education
from .language import Language
from .scoring_result import ScoringResult
